"""
Django settings for transcendence project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables desde el archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d1g8r#l8#dhl5^i!-wu07rk$xa9hwf1jj9g@gh!q9jyf6g^sgb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['devcontainer', 'localhost', '127.0.0.1', 'django', 'http://c1r1s1.42madrid.com:8000/oauth/callback', 'http://c1r1s2.42madrid.com:8000/oauth/callback', 'http://c1r1s3.42madrid.com:8000/oauth/callback', 'http://c1r1s4.42madrid.com:8000/oauth/callback', 'http://c1r1s5.42madrid.com:8000/oauth/callback', 'http://c1r1s6.42madrid.com:8000/oauth/callback', 'http://c1r2s1.42madrid.com:8000/oauth/callback', 'http://c1r2s2.42madrid.com:8000/oauth/callback', 'http://c1r2s3.42madrid.com:8000/oauth/callback', 'http://c1r2s4.42madrid.com:8000/oauth/callback', 'http://c1r2s5.42madrid.com:8000/oauth/callback', 'http://c1r2s6.42madrid.com:8000/oauth/callback', 'http://c1r3s1.42madrid.com:8000/oauth/callback', 'http://c1r3s2.42madrid.com:8000/oauth/callback', 'http://c1r3s3.42madrid.com:8000/oauth/callback', 'http://c1r3s4.42madrid.com:8000/oauth/callback', 'http://c1r3s5.42madrid.com:8000/oauth/callback', 'http://c1r3s6.42madrid.com:8000/oauth/callback', 'http://c1r4s1.42madrid.com:8000/oauth/callback', 'http://c1r4s2.42madrid.com:8000/oauth/callback', 'http://c1r4s3.42madrid.com:8000/oauth/callback', 'http://c1r4s4.42madrid.com:8000/oauth/callback', 'http://c1r4s5.42madrid.com:8000/oauth/callback', 'http://c1r4s6.42madrid.com:8000/oauth/callback', 'http://c1r5s1.42madrid.com:8000/oauth/callback', 'http://c1r5s2.42madrid.com:8000/oauth/callback', 'http://c1r5s3.42madrid.com:8000/oauth/callback', 'http://c1r5s4.42madrid.com:8000/oauth/callback', 'http://c1r5s5.42madrid.com:8000/oauth/callback', 'http://c1r5s6.42madrid.com:8000/oauth/callback', 'http://c1r6s1.42madrid.com:8000/oauth/callback', 'http://c1r6s2.42madrid.com:8000/oauth/callback', 'http://c1r6s3.42madrid.com:8000/oauth/callback', 'http://c1r6s4.42madrid.com:8000/oauth/callback', 'http://c1r6s5.42madrid.com:8000/oauth/callback', 'http://c1r6s6.42madrid.com:8000/oauth/callback', 'http://c1r7s1.42madrid.com:8000/oauth/callback', 'http://c1r7s2.42madrid.com:8000/oauth/callback', 'http://c1r7s3.42madrid.com:8000/oauth/callback', 'http://c1r7s4.42madrid.com:8000/oauth/callback', 'http://c1r7s5.42madrid.com:8000/oauth/callback', 'http://c1r7s6.42madrid.com:8000/oauth/callback', 'http://c1r8s1.42madrid.com:8000/oauth/callback', 'http://c1r8s2.42madrid.com:8000/oauth/callback', 'http://c1r8s3.42madrid.com:8000/oauth/callback', 'http://c1r8s4.42madrid.com:8000/oauth/callback', 'http://c1r8s5.42madrid.com:8000/oauth/callback', 'http://c1r8s6.42madrid.com:8000/oauth/callback', 'http://c1r9s1.42madrid.com:8000/oauth/callback', 'http://c1r9s2.42madrid.com:8000/oauth/callback', 'http://c1r9s3.42madrid.com:8000/oauth/callback', 'http://c1r9s4.42madrid.com:8000/oauth/callback', 'http://c1r9s5.42madrid.com:8000/oauth/callback', 'http://c1r9s6.42madrid.com:8000/oauth/callback', 'http://c1r10s1.42madrid.com:8000/oauth/callback', 'http://c1r10s2.42madrid.com:8000/oauth/callback', 'http://c1r10s3.42madrid.com:8000/oauth/callback', 'http://c1r10s4.42madrid.com:8000/oauth/callback', 'http://c1r10s5.42madrid.com:8000/oauth/callback', 'http://c1r10s6.42madrid.com:8000/oauth/callback', 'http://c1r11s1.42madrid.com:8000/oauth/callback', 'http://c1r11s2.42madrid.com:8000/oauth/callback', 'http://c1r11s3.42madrid.com:8000/oauth/callback', 'http://c1r11s4.42madrid.com:8000/oauth/callback', 'http://c1r11s5.42madrid.com:8000/oauth/callback', 'http://c1r11s6.42madrid.com:8000/oauth/callback', 'http://c1r12s1.42madrid.com:8000/oauth/callback', 'http://c1r12s2.42madrid.com:8000/oauth/callback', 'http://c1r12s3.42madrid.com:8000/oauth/callback', 'http://c1r12s4.42madrid.com:8000/oauth/callback', 'http://c1r12s5.42madrid.com:8000/oauth/callback', 'http://c1r12s6.42madrid.com:8000/oauth/callback', 'http://c1r13s1.42madrid.com:8000/oauth/callback', 'http://c1r13s2.42madrid.com:8000/oauth/callback', 'http://c1r13s3.42madrid.com:8000/oauth/callback', 'http://c1r13s4.42madrid.com:8000/oauth/callback', 'http://c1r13s5.42madrid.com:8000/oauth/callback', 'http://c1r13s6.42madrid.com:8000/oauth/callback', 'http://c1r14s1.42madrid.com:8000/oauth/callback', 'http://c1r14s2.42madrid.com:8000/oauth/callback', 'http://c1r14s3.42madrid.com:8000/oauth/callback', 'http://c1r14s4.42madrid.com:8000/oauth/callback', 'http://c1r14s5.42madrid.com:8000/oauth/callback', 'http://c1r14s6.42madrid.com:8000/oauth/callback', 'http://c1r15s1.42madrid.com:8000/oauth/callback', 'http://c1r15s2.42madrid.com:8000/oauth/callback', 'http://c1r15s3.42madrid.com:8000/oauth/callback', 'http://c1r15s4.42madrid.com:8000/oauth/callback', 'http://c1r15s5.42madrid.com:8000/oauth/callback', 'http://c1r15s6.42madrid.com:8000/oauth/callback', 'http://c1r16s1.42madrid.com:8000/oauth/callback', 'http://c1r16s2.42madrid.com:8000/oauth/callback', 'http://c1r16s3.42madrid.com:8000/oauth/callback', 'http://c1r16s4.42madrid.com:8000/oauth/callback', 'http://c1r16s5.42madrid.com:8000/oauth/callback', 'http://c1r16s6.42madrid.com:8000/oauth/callback', 'http://c1r17s1.42madrid.com:8000/oauth/callback', 'http://c1r17s2.42madrid.com:8000/oauth/callback', 'http://c1r17s3.42madrid.com:8000/oauth/callback', 'http://c1r17s4.42madrid.com:8000/oauth/callback', 'http://c1r17s5.42madrid.com:8000/oauth/callback', 'http://c1r17s6.42madrid.com:8000/oauth/callback', 'http://c1r18s1.42madrid.com:8000/oauth/callback', 'http://c1r18s2.42madrid.com:8000/oauth/callback', 'http://c1r18s3.42madrid.com:8000/oauth/callback', 'http://c1r18s4.42madrid.com:8000/oauth/callback', 'http://c1r18s5.42madrid.com:8000/oauth/callback', 'http://c1r18s6.42madrid.com:8000/oauth/callback', 'http://c1r19s1.42madrid.com:8000/oauth/callback', 'http://c1r19s2.42madrid.com:8000/oauth/callback', 'http://c1r19s3.42madrid.com:8000/oauth/callback', 'http://c1r19s4.42madrid.com:8000/oauth/callback', 'http://c1r19s5.42madrid.com:8000/oauth/callback', 'http://c1r19s6.42madrid.com:8000/oauth/callback', 'http://c2r1s1.42madrid.com:8000/oauth/callback', 'http://c2r1s2.42madrid.com:8000/oauth/callback', 'http://c2r1s3.42madrid.com:8000/oauth/callback', 'http://c2r1s4.42madrid.com:8000/oauth/callback', 'http://c2r1s5.42madrid.com:8000/oauth/callback', 'http://c2r1s6.42madrid.com:8000/oauth/callback', 'http://c2r2s1.42madrid.com:8000/oauth/callback', 'http://c2r2s2.42madrid.com:8000/oauth/callback', 'http://c2r2s3.42madrid.com:8000/oauth/callback', 'http://c2r2s4.42madrid.com:8000/oauth/callback', 'http://c2r2s5.42madrid.com:8000/oauth/callback', 'http://c2r2s6.42madrid.com:8000/oauth/callback', 'http://c2r3s1.42madrid.com:8000/oauth/callback', 'http://c2r3s2.42madrid.com:8000/oauth/callback', 'http://c2r3s3.42madrid.com:8000/oauth/callback', 'http://c2r3s4.42madrid.com:8000/oauth/callback', 'http://c2r3s5.42madrid.com:8000/oauth/callback', 'http://c2r3s6.42madrid.com:8000/oauth/callback', 'http://c2r4s1.42madrid.com:8000/oauth/callback', 'http://c2r4s2.42madrid.com:8000/oauth/callback', 'http://c2r4s3.42madrid.com:8000/oauth/callback', 'http://c2r4s4.42madrid.com:8000/oauth/callback', 'http://c2r4s5.42madrid.com:8000/oauth/callback', 'http://c2r4s6.42madrid.com:8000/oauth/callback', 'http://c2r5s1.42madrid.com:8000/oauth/callback', 'http://c2r5s2.42madrid.com:8000/oauth/callback', 'http://c2r5s3.42madrid.com:8000/oauth/callback', 'http://c2r5s4.42madrid.com:8000/oauth/callback', 'http://c2r5s5.42madrid.com:8000/oauth/callback', 'http://c2r5s6.42madrid.com:8000/oauth/callback', 'http://c2r6s1.42madrid.com:8000/oauth/callback', 'http://c2r6s2.42madrid.com:8000/oauth/callback', 'http://c2r6s3.42madrid.com:8000/oauth/callback', 'http://c2r6s4.42madrid.com:8000/oauth/callback', 'http://c2r6s5.42madrid.com:8000/oauth/callback', 'http://c2r6s6.42madrid.com:8000/oauth/callback', 'http://c2r7s1.42madrid.com:8000/oauth/callback', 'http://c2r7s2.42madrid.com:8000/oauth/callback', 'http://c2r7s3.42madrid.com:8000/oauth/callback', 'http://c2r7s4.42madrid.com:8000/oauth/callback', 'http://c2r7s5.42madrid.com:8000/oauth/callback', 'http://c2r7s6.42madrid.com:8000/oauth/callback', 'http://c2r8s1.42madrid.com:8000/oauth/callback', 'http://c2r8s2.42madrid.com:8000/oauth/callback', 'http://c2r8s3.42madrid.com:8000/oauth/callback', 'http://c2r8s4.42madrid.com:8000/oauth/callback', 'http://c2r8s5.42madrid.com:8000/oauth/callback', 'http://c2r8s6.42madrid.com:8000/oauth/callback', 'http://c2r9s1.42madrid.com:8000/oauth/callback', 'http://c2r9s2.42madrid.com:8000/oauth/callback', 'http://c2r9s3.42madrid.com:8000/oauth/callback', 'http://c2r9s4.42madrid.com:8000/oauth/callback', 'http://c2r9s5.42madrid.com:8000/oauth/callback', 'http://c2r9s6.42madrid.com:8000/oauth/callback', 'http://c2r10s1.42madrid.com:8000/oauth/callback', 'http://c2r10s2.42madrid.com:8000/oauth/callback', 'http://c2r10s3.42madrid.com:8000/oauth/callback',
                 'http://c2r10s4.42madrid.com:8000/oauth/callback', 'http://c2r10s5.42madrid.com:8000/oauth/callback', 'http://c2r10s6.42madrid.com:8000/oauth/callback', 'http://c2r11s1.42madrid.com:8000/oauth/callback', 'http://c2r11s2.42madrid.com:8000/oauth/callback', 'http://c2r11s3.42madrid.com:8000/oauth/callback', 'http://c2r11s4.42madrid.com:8000/oauth/callback', 'http://c2r11s5.42madrid.com:8000/oauth/callback', 'http://c2r11s6.42madrid.com:8000/oauth/callback', 'http://c2r12s1.42madrid.com:8000/oauth/callback', 'http://c2r12s2.42madrid.com:8000/oauth/callback', 'http://c2r12s3.42madrid.com:8000/oauth/callback', 'http://c2r12s4.42madrid.com:8000/oauth/callback', 'http://c2r12s5.42madrid.com:8000/oauth/callback', 'http://c2r12s6.42madrid.com:8000/oauth/callback', 'http://c2r13s1.42madrid.com:8000/oauth/callback', 'http://c2r13s2.42madrid.com:8000/oauth/callback', 'http://c2r13s3.42madrid.com:8000/oauth/callback', 'http://c2r13s4.42madrid.com:8000/oauth/callback', 'http://c2r13s5.42madrid.com:8000/oauth/callback', 'http://c2r13s6.42madrid.com:8000/oauth/callback', 'http://c2r14s1.42madrid.com:8000/oauth/callback', 'http://c2r14s2.42madrid.com:8000/oauth/callback', 'http://c2r14s3.42madrid.com:8000/oauth/callback', 'http://c2r14s4.42madrid.com:8000/oauth/callback', 'http://c2r14s5.42madrid.com:8000/oauth/callback', 'http://c2r14s6.42madrid.com:8000/oauth/callback', 'http://c2r15s1.42madrid.com:8000/oauth/callback', 'http://c2r15s2.42madrid.com:8000/oauth/callback', 'http://c2r15s3.42madrid.com:8000/oauth/callback', 'http://c2r15s4.42madrid.com:8000/oauth/callback', 'http://c2r15s5.42madrid.com:8000/oauth/callback', 'http://c2r15s6.42madrid.com:8000/oauth/callback', 'http://c2r16s1.42madrid.com:8000/oauth/callback', 'http://c2r16s2.42madrid.com:8000/oauth/callback', 'http://c2r16s3.42madrid.com:8000/oauth/callback', 'http://c2r16s4.42madrid.com:8000/oauth/callback', 'http://c2r16s5.42madrid.com:8000/oauth/callback', 'http://c2r16s6.42madrid.com:8000/oauth/callback', 'http://c2r17s1.42madrid.com:8000/oauth/callback', 'http://c2r17s2.42madrid.com:8000/oauth/callback', 'http://c2r17s3.42madrid.com:8000/oauth/callback', 'http://c2r17s4.42madrid.com:8000/oauth/callback', 'http://c2r17s5.42madrid.com:8000/oauth/callback', 'http://c2r17s6.42madrid.com:8000/oauth/callback', 'http://c2r18s1.42madrid.com:8000/oauth/callback', 'http://c2r18s2.42madrid.com:8000/oauth/callback', 'http://c2r18s3.42madrid.com:8000/oauth/callback', 'http://c2r18s4.42madrid.com:8000/oauth/callback', 'http://c2r18s5.42madrid.com:8000/oauth/callback', 'http://c2r18s6.42madrid.com:8000/oauth/callback', 'http://c2r19s1.42madrid.com:8000/oauth/callback', 'http://c2r19s2.42madrid.com:8000/oauth/callback', 'http://c2r19s3.42madrid.com:8000/oauth/callback', 'http://c2r19s4.42madrid.com:8000/oauth/callback', 'http://c2r19s5.42madrid.com:8000/oauth/callback', 'http://c2r19s6.42madrid.com:8000/oauth/callback', 'http://c3r1s1.42madrid.com:8000/oauth/callback', 'http://c3r1s2.42madrid.com:8000/oauth/callback', 'http://c3r1s3.42madrid.com:8000/oauth/callback', 'http://c3r1s4.42madrid.com:8000/oauth/callback', 'http://c3r1s5.42madrid.com:8000/oauth/callback', 'http://c3r1s6.42madrid.com:8000/oauth/callback', 'http://c3r2s1.42madrid.com:8000/oauth/callback', 'http://c3r2s2.42madrid.com:8000/oauth/callback', 'http://c3r2s3.42madrid.com:8000/oauth/callback', 'http://c3r2s4.42madrid.com:8000/oauth/callback', 'http://c3r2s5.42madrid.com:8000/oauth/callback', 'http://c3r2s6.42madrid.com:8000/oauth/callback', 'http://c3r3s1.42madrid.com:8000/oauth/callback', 'http://c3r3s2.42madrid.com:8000/oauth/callback', 'http://c3r3s3.42madrid.com:8000/oauth/callback', 'http://c3r3s4.42madrid.com:8000/oauth/callback', 'http://c3r3s5.42madrid.com:8000/oauth/callback', 'http://c3r3s6.42madrid.com:8000/oauth/callback', 'http://c3r4s1.42madrid.com:8000/oauth/callback', 'http://c3r4s2.42madrid.com:8000/oauth/callback', 'http://c3r4s3.42madrid.com:8000/oauth/callback', 'http://c3r4s4.42madrid.com:8000/oauth/callback', 'http://c3r4s5.42madrid.com:8000/oauth/callback', 'http://c3r4s6.42madrid.com:8000/oauth/callback', 'http://c3r5s1.42madrid.com:8000/oauth/callback', 'http://c3r5s2.42madrid.com:8000/oauth/callback', 'http://c3r5s3.42madrid.com:8000/oauth/callback', 'http://c3r5s4.42madrid.com:8000/oauth/callback', 'http://c3r5s5.42madrid.com:8000/oauth/callback', 'http://c3r5s6.42madrid.com:8000/oauth/callback', 'http://c3r6s1.42madrid.com:8000/oauth/callback', 'http://c3r6s2.42madrid.com:8000/oauth/callback', 'http://c3r6s3.42madrid.com:8000/oauth/callback', 'http://c3r6s4.42madrid.com:8000/oauth/callback', 'http://c3r6s5.42madrid.com:8000/oauth/callback', 'http://c3r6s6.42madrid.com:8000/oauth/callback', 'http://c3r7s1.42madrid.com:8000/oauth/callback', 'http://c3r7s2.42madrid.com:8000/oauth/callback', 'http://c3r7s3.42madrid.com:8000/oauth/callback', 'http://c3r7s4.42madrid.com:8000/oauth/callback', 'http://c3r7s5.42madrid.com:8000/oauth/callback', 'http://c3r7s6.42madrid.com:8000/oauth/callback', 'http://c3r8s1.42madrid.com:8000/oauth/callback', 'http://c3r8s2.42madrid.com:8000/oauth/callback', 'http://c3r8s3.42madrid.com:8000/oauth/callback', 'http://c3r8s4.42madrid.com:8000/oauth/callback', 'http://c3r8s5.42madrid.com:8000/oauth/callback', 'http://c3r8s6.42madrid.com:8000/oauth/callback', 'http://c3r9s1.42madrid.com:8000/oauth/callback', 'http://c3r9s2.42madrid.com:8000/oauth/callback', 'http://c3r9s3.42madrid.com:8000/oauth/callback', 'http://c3r9s4.42madrid.com:8000/oauth/callback', 'http://c3r9s5.42madrid.com:8000/oauth/callback', 'http://c3r9s6.42madrid.com:8000/oauth/callback', 'http://c3r10s1.42madrid.com:8000/oauth/callback', 'http://c3r10s2.42madrid.com:8000/oauth/callback', 'http://c3r10s3.42madrid.com:8000/oauth/callback', 'http://c3r10s4.42madrid.com:8000/oauth/callback', 'http://c3r10s5.42madrid.com:8000/oauth/callback', 'http://c3r10s6.42madrid.com:8000/oauth/callback', 'http://c3r11s1.42madrid.com:8000/oauth/callback', 'http://c3r11s2.42madrid.com:8000/oauth/callback', 'http://c3r11s3.42madrid.com:8000/oauth/callback', 'http://c3r11s4.42madrid.com:8000/oauth/callback', 'http://c3r11s5.42madrid.com:8000/oauth/callback', 'http://c3r11s6.42madrid.com:8000/oauth/callback', 'http://c3r12s1.42madrid.com:8000/oauth/callback', 'http://c3r12s2.42madrid.com:8000/oauth/callback', 'http://c3r12s3.42madrid.com:8000/oauth/callback', 'http://c3r12s4.42madrid.com:8000/oauth/callback', 'http://c3r12s5.42madrid.com:8000/oauth/callback', 'http://c3r12s6.42madrid.com:8000/oauth/callback', 'http://c3r13s1.42madrid.com:8000/oauth/callback', 'http://c3r13s2.42madrid.com:8000/oauth/callback', 'http://c3r13s3.42madrid.com:8000/oauth/callback', 'http://c3r13s4.42madrid.com:8000/oauth/callback', 'http://c3r13s5.42madrid.com:8000/oauth/callback', 'http://c3r13s6.42madrid.com:8000/oauth/callback', 'http://c3r14s1.42madrid.com:8000/oauth/callback', 'http://c3r14s2.42madrid.com:8000/oauth/callback', 'http://c3r14s3.42madrid.com:8000/oauth/callback', 'http://c3r14s4.42madrid.com:8000/oauth/callback', 'http://c3r14s5.42madrid.com:8000/oauth/callback', 'http://c3r14s6.42madrid.com:8000/oauth/callback', 'http://c3r15s1.42madrid.com:8000/oauth/callback', 'http://c3r15s2.42madrid.com:8000/oauth/callback', 'http://c3r15s3.42madrid.com:8000/oauth/callback', 'http://c3r15s4.42madrid.com:8000/oauth/callback', 'http://c3r15s5.42madrid.com:8000/oauth/callback', 'http://c3r15s6.42madrid.com:8000/oauth/callback', 'http://c3r16s1.42madrid.com:8000/oauth/callback', 'http://c3r16s2.42madrid.com:8000/oauth/callback', 'http://c3r16s3.42madrid.com:8000/oauth/callback', 'http://c3r16s4.42madrid.com:8000/oauth/callback', 'http://c3r16s5.42madrid.com:8000/oauth/callback', 'http://c3r16s6.42madrid.com:8000/oauth/callback', 'http://c3r17s1.42madrid.com:8000/oauth/callback', 'http://c3r17s2.42madrid.com:8000/oauth/callback', 'http://c3r17s3.42madrid.com:8000/oauth/callback', 'http://c3r17s4.42madrid.com:8000/oauth/callback', 'http://c3r17s5.42madrid.com:8000/oauth/callback', 'http://c3r17s6.42madrid.com:8000/oauth/callback', 'http://c3r18s1.42madrid.com:8000/oauth/callback', 'http://c3r18s2.42madrid.com:8000/oauth/callback', 'http://c3r18s3.42madrid.com:8000/oauth/callback', 'http://c3r18s4.42madrid.com:8000/oauth/callback', 'http://c3r18s5.42madrid.com:8000/oauth/callback', 'http://c3r18s6.42madrid.com:8000/oauth/callback', 'http://c3r19s1.42madrid.com:8000/oauth/callback', 'http://c3r19s2.42madrid.com:8000/oauth/callback', 'http://c3r19s3.42madrid.com:8000/oauth/callback', 'http://c3r19s4.42madrid.com:8000/oauth/callback', 'http://c3r19s5.42madrid.com:8000/oauth/callback', 'http://c3r19s6.42madrid.com:8000/oauth/callback']

# 42 OAuth Settings
OAUTH_42_CLIENT_ID = os.getenv("OAUTH_42_CLIENT_ID")
OAUTH_42_CLIENT_SECRET = os.getenv("OAUTH_42_CLIENT_SECRET")
# OAUTH_42_REDIRECT_URI = 'http://127.0.0.1:8000/oauth/callback'
OAUTH_42_REDIRECT_URI = os.getenv(
    "CAMPUS_HOST", "localhost") + ':8000/oauth/callback'
OAUTH_42_AUTHORIZATION_URL = 'https://api.intra.42.fr/oauth/authorize'
OAUTH_42_TOKEN_URL = 'https://api.intra.42.fr/oauth/token'
OAUTH_42_API_URL = 'https://api.intra.42.fr/v2/me'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'bootstrap5',
    'django_htmx',
    'django_prometheus',
    'channels',
    'users',
    'pong',
]

MIDDLEWARE = [
    # Prometheus debe ser el primero
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise para servir archivos estáticos
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    # Prometheus debe ser el último
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    # 'users.middleware.AuthRequiredMiddleware',
]

ROOT_URLCONF = 'transcendence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.user_data',
            ],
        },
    },
]

ASGI_APPLICATION = 'transcendence.asgi.application'
WSGI_APPLICATION = 'transcendence.wsgi.application'

REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", None)

"""
# Este provoca fallos en pong multijugador, en su lugar usamos el de debajo.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "host": REDIS_HOST,
                    "port": REDIS_PORT,
                    "password": REDIS_PASSWORD
                }
            ],
        },
    },
}
"""

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "host": REDIS_HOST,
                    "port": REDIS_PORT,
                    "password": REDIS_PASSWORD
                }
            ],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_USER = os.getenv("POSTGRES_USER")
DB_PASSWORD = os.getenv("POSTGRES_PASSWORD")
DB_NAME = os.getenv("POSTGRES_DB")
DB_PORT = os.getenv("POSTGRES_PORT")

DATABASES = {
    'default': {
        'ENGINE': 'django_prometheus.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': 'db',
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PROMETHEUS CONFIG
PROMETHEUS_EXPORT_MIGRATIONS = True
