# Generated by Django 4.2.19 on 2025-03-03 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False)),
                ('intra_id', models.IntegerField(unique=True)),
                ('intra_picture', models.URLField(blank=True, max_length=255, null=True)),
                ('intra_login', models.CharField(max_length=100, unique=True)),
                ('intra_name', models.CharField(max_length=100)),
                ('intra_surname', models.CharField(max_length=100)),
                ('internal_login', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('internal_picture', models.URLField(blank=True, max_length=255, null=True)),
                ('user_creation', models.DateTimeField(auto_now_add=True)),
                ('last_online', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
