# Generated by Django 4.2.19 on 2025-03-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_intra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intra_login',
            field=models.CharField(max_length=100),
        ),
    ]
