# Generated by Django 4.2.19 on 2025-03-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_games_played_user_games_won_user_total_points'),
        ('users', '0003_alter_user_intra_login'),
    ]

    operations = [
    ]
