# Generated by Django 4.2.19 on 2025-04-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250310_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='internal_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
