# Generated by Django 4.2.19 on 2025-04-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_internal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='internal_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
