# Generated by Django 4.2.19 on 2025-04-16 16:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_internal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='internal_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_picture_path),
        ),
    ]
